Garmin has deprecated its legacy authentication
magsol/garmin pull request #20
Opened 2018-04-11 14:24 UTC by AngelaKru

About 5 or 6 days ago, my garmin downloader stopped working. The old GAUTH URL is down and seems to have been replaced fully by the newer 'modern' pages. After some googling and testing on my local copy, I was able to get my downloads working again (Python 2.7 which still allows use of Mechanize package)
The JSON returned by the new activity service is no longer a nicely formatted recordset, but rather just a list of json activities, and some of the field names have changed (beginTimestamp is now just an int and seems replaced by startTimeLocal for example). And no more nice little summary with totalActivities count...

2018-04-11 23:17 UTC, magsol requested changes

2018-04-11 23:17 UTC, magsol commented on download.py
> +    #totalActivities = int(search['results']['totalFound']) ##we no longer have a nice little batch summary, just an array of JSON activities
Go ahead and delete the commented-out code; version control will keep track of it anyway.

2018-04-12 07:38 UTC, AngelaKru commented
There ya go, old commented out code removed :)

2018-04-12 14:47 UTC, merged

2018-04-12 14:47 UTC, magsol commented
Fantastic, THANK YOU!